### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by CravateRouge** [CravateRouge/CravateRouge.github.io#2]
- [ ] Add bloodyAD logo
- [ ] Add twitter in footer
- [ ] Add RSS Feed in footer
- [ ] Add "edit me on github" on top right of all pages
- [ ] Add drop down menu and dedicated page with articles organized by category
